#ifndef INDUVIEWERCORE_GLOBAL_H
#define INDUVIEWERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INDUVIEWERCORE_LIBRARY)
#  define INDUVIEWERCORE_EXPORT Q_DECL_EXPORT
#else
#  define INDUVIEWERCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // INDUVIEWERCORE_GLOBAL_H
